disabled_rules:
  - line_length
  - force_try
  - force_cast
  - operator_whitespace
  - trailing_whitespace
  - todo
  - closure_parameter_position
  - large_tuple
  - unused_optional_binding

line_length:
  error: 120

type_body_length:
  error: 100

file_length:
  error: 200

function_body_length:
  error: 20

reporter: "xcode"
