language: swift
osx_image: xcode9

install:

- gem install xcpretty-travis-formatter
# - ./install_swiftlint.sh

script:

- xcodebuild -project ./Designpatterns/DesignPatterns/DesignPatterns.xcodeproj -scheme Designpatterns | xcpretty -f `xcpretty-travis-formatter`
