language: swift
osx_image: xcode9

install:

- gem install xcpretty-travis-formatter
# - ./install_swiftlint.sh

script:
- xcodebuild -project ./DesignPatterns/DesignPatterns.xcodeproj -scheme DesignPatterns | xcpretty -f `xcpretty-travis-formatter`
